apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: Tata Power
      defaultBucket: power
      tlsSkipVerify: true
    secureJsonData:
      token: cdbec302fa00a707cd3ff98822f0c9b95296768ba503517bc342e0e39be38b7c