version: "3"

services:  
  grafana:
    image: grafana/grafana-oss:9.3.2
    volumes:
      - ./dashboards:/etc/dashboards
      - ./provisioning/:/etc/grafana/provisioning/
      - grafana-storage:/var/lib/grafana:rw
    #depends_on:
      #- influxdb
    ports:
      #- ${GRAFANA_PORT}:3000
      - "3000:3000"
      
volumes:
  grafana-storage:

networks: 
  default: 
    external: 
      name: tatapower
    

