# config file version
apiVersion: 1


# List of contact points to import or update

contactPoints:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the contact point
    name: telegram
    receivers:
      # <string, required> unique identifier for the receiver
      - uid: KNKdqVp4k
        # <string, required> type of the receiver
        type: telegram
        # <object, required> settings for the specific receiver type
        settings:
          bottoken: 5818330332:AAGhvdWAe6xXezcx6Yxc_jxpVPtz4NP3eeg
          # <string, required>
          chatid: 1099845479
          # <string>
          message: |
            {{ template "telegram.message" . }}
          
          
deleteContactPoints:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> unique identifier for the receiver
    uid: KNKdqVp4k

# List of notification policies
policies:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string> name of the contact point that should be used for this route
    receiver: telegram
    # <list> The labels by which incoming alerts are grouped together. For example,
    #        multiple alerts coming in for cluster=A and alertname=LatencyHigh would
    #        be batched into a single group.
    #
    #        To aggregate by all possible labels use the special value '...' as
    #        the sole label name, for example:
    #        group_by: ['...']
    #        This effectively disables aggregation entirely, passing through all
    #        alerts as-is. This is unlikely to be what you want, unless you have
    #        a very low alert volume or your upstream notification system performs
    #        its own grouping.
    #group_by: ['...']
    # <list> a list of matchers that an alert has to fulfill to match the node
    #matchers:
     # - alertname = Watchdog
     # - severity =~ "warning|critical"
    # <list> Times when the route should be muted. These must match the name of a
    #        mute time interval.
    #        Additionally, the root node cannot have any mute times.
    #        When a route is muted it will not send any notifications, but
    #        otherwise acts normally (including ending the route-matching process
    #        if the `continue` option is not set)
    #mute_time_intervals:
    #  - abc
    # <duration> How long to initially wait to send a notification for a group
    #            of alerts. Allows to collect more initial alerts for the same group.
    #            (Usually ~0s to few minutes), default = 30s
    group_wait: 5s
    # <duration> How long to wait before sending a notification about new alerts that
    #            are added to a group of alerts for which an initial notification has
    #            already been sent. (Usually ~5m or more), default = 5m
    group_interval: 5s
    # <duration>  How long to wait before sending a notification again if it has already
    #             been sent successfully for an alert. (Usually ~3h or more), default = 4h
    repeat_interval: 5s
    # <list> Zero or more child routes
    # routes:
    # ...
    
    
# config file version

# List of orgIds that should be reset to the default policy
resetPolicies:
  - 1
    
    
    
